---
app_db_host: "{{ hostvars[groups['db'][0]]['ansible_default_ipv4']['address'] }}"

# proxy
nginx_sites:
  default:
    - listen 80 default_server
    - server_name _
    - location / {
        proxy_pass http://127.0.0.1:9292;
      }
