---
- name: Deploy App
  hosts: app

  tasks:
   - name: Fetch the latest version of application code
     git:
      repo: 'https://github.com/express42/reddit.git'
      dest: /home/appuser/reddit
      version: monolith
     notify: restart puma

   - name: Bundle install
     bundler:
      state: present
      chdir: /home/appuser/reddit
     register: bundle_install_result
     until: bundle_install_result is success

  handlers:
   - name: restart puma
     become: true
     service:
      name: puma
      state: restarted
