---
  - name: Install ruby and rubygems and required packages
    apt:
     name: "{{ ruby_packages }}"
     state: present
     update_cache: yes
    register: ruby_packages_result
    until: ruby_packages_result is success
